-- Миграция: расширение схемы partners для карточки партнера (CRUD)
-- Справочник типов партнера + поля, заданные в форме

CREATE TABLE IF NOT EXISTS public.partner_types (
    partner_type_id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_type_name varchar(100) NOT NULL UNIQUE
);

INSERT INTO public.partner_types (partner_type_name) VALUES ('ЗАО')
ON CONFLICT (partner_type_name) DO NOTHING;
INSERT INTO public.partner_types (partner_type_name) VALUES ('ООО')
ON CONFLICT (partner_type_name) DO NOTHING;
INSERT INTO public.partner_types (partner_type_name) VALUES ('ИП')
ON CONFLICT (partner_type_name) DO NOTHING;
INSERT INTO public.partner_types (partner_type_name) VALUES ('ЧП')
ON CONFLICT (partner_type_name) DO NOTHING;
INSERT INTO public.partner_types (partner_type_name) VALUES ('АО')
ON CONFLICT (partner_type_name) DO NOTHING;
INSERT INTO public.partner_types (partner_type_name) VALUES ('ПАО')
ON CONFLICT (partner_type_name) DO NOTHING;

ALTER TABLE public.partners
    ADD COLUMN IF NOT EXISTS partner_type_id smallint
        CONSTRAINT partners_partner_type_id_fkey REFERENCES public.partner_types(partner_type_id),
    ADD COLUMN IF NOT EXISTS legal_address varchar,
    ADD COLUMN IF NOT EXISTS director_name varchar;

CREATE INDEX IF NOT EXISTS idx_partners_partner_type_id
    ON public.partners(partner_type_id);