-- Миграция: справочники для ядра расчета материалов
-- product_types — коэффициент типа продукции (множитель базового расхода)
-- material_types — процент брака материала (доля дополнительного расхода)

CREATE TABLE IF NOT EXISTS public.product_types (
    product_type_id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name varchar(100) NOT NULL UNIQUE,
    -- Коэффициент типа продукции: положительное число, увеличивает базовый расход
    coefficient numeric(10, 4) NOT NULL CHECK (coefficient > 0)
);

CREATE TABLE IF NOT EXISTS public.material_types (
    material_type_id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name varchar(100) NOT NULL UNIQUE,
    -- Процент брака: доля от 0 до 100, добавляется к чистому расходу
    defect_percent numeric(5, 2) NOT NULL CHECK (defect_percent >= 0 AND defect_percent <= 100)
);

INSERT INTO public.product_types (type_name, coefficient) VALUES ('Бытовая техника', 1.2)
ON CONFLICT (type_name) DO NOTHING;
INSERT INTO public.product_types (type_name, coefficient) VALUES ('Электроника', 1.0)
ON CONFLICT (type_name) DO NOTHING;
INSERT INTO public.product_types (type_name, coefficient) VALUES ('Строительные материалы', 1.5)
ON CONFLICT (type_name) DO NOTHING;
INSERT INTO public.product_types (type_name, coefficient) VALUES ('Текстиль', 0.8)
ON CONFLICT (type_name) DO NOTHING;
INSERT INTO public.product_types (type_name, coefficient) VALUES ('Продукты питания', 1.1)
ON CONFLICT (type_name) DO NOTHING;

INSERT INTO public.material_types (type_name, defect_percent) VALUES ('Металл', 5.0)
ON CONFLICT (type_name) DO NOTHING;
INSERT INTO public.material_types (type_name, defect_percent) VALUES ('Пластик', 3.0)
ON CONFLICT (type_name) DO NOTHING;
INSERT INTO public.material_types (type_name, defect_percent) VALUES ('Электронные компоненты', 2.0)
ON CONFLICT (type_name) DO NOTHING;
INSERT INTO public.material_types (type_name, defect_percent) VALUES ('Ткань', 7.0)
ON CONFLICT (type_name) DO NOTHING;
INSERT INTO public.material_types (type_name, defect_percent) VALUES ('Сыпучие материалы', 4.0)
ON CONFLICT (type_name) DO NOTHING;
INSERT INTO public.material_types (type_name, defect_percent) VALUES ('Стекло', 6.0)
ON CONFLICT (type_name) DO NOTHING;
